### PR TITLE
selector-no-redundant-nesting-selector: Add support for Dart Sass deprecation

### PR DESCRIPTION
**Pull request by kristerkari**
Related to #1020

### CODE REVIEW

**Comment by Mister-Hope** [comment]
LGTM, but see https://github.com/sass/dart-sass/issues/2276#issue-2399880250

As we can revert this change back once the new behavior is activated, so this change might better be opt-in with a new rule option.

**Comment by kristerkari** [comment]
> LGTM, but see [sass/dart-sass#2276 (comment)](https://github.com/sass/dart-sass/issues/2276#issue-2399880250)

Thanks, I'll need to read through the comments to understand what's going on 😄

**Comment by kristerkari** [comment]
> As we can revert this change back once the new behavior is activated, so this change might better be opt-in with a new rule option.

Yeah, I can also put it behind a rule option for opt-in.

**Comment by Mister-Hope** [comment]
Any update with this as it has been a while?

**Comment by kristerkari** [comment]
I actually I forgot to follow up on this, sorry @Mister-Hope 

I still need to read through the 47 comments 😁

**Pull request merged**
