### PR TITLE
CI: add Node.js 20

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Review by kristerkari — APPROVED** [review]
Looks good 👍

**Comment by XhmikosR** [comment]
Nice! Can you also cut a v5.0.0 release?

**Comment by kristerkari** [comment]
yes, I can!

**Comment by XhmikosR** [comment]
Thanks!

Just remember to use npm 8.x due to https://github.com/npm/cli/issues/6341. Not a huge deal if you don't, but it won't be how slim the tar would be if that bug didn't exist.

**Pull request merged**
